import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:wallbox_logs/back_layer/model_repos/simulation_repo/user_master/simulation_repo.dart';
import 'package:wallbox_logs/mid_layer/services/database_model.dart';
import 'package:wallbox_logs/mid_layer/services/user_master/user_master_data.dart';
import 'package:wallbox_logs/utility.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'wall_box_transaction.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'wall_box_transaction.g.dart';

/// In this class we keep every time somebody charged their vehicle at a wallbox
/// We keep data about the begin and end oft the charging process and can recieve how much power was used
///
/// This class stores completed processes only!
@freezed
@JsonSerializable()
class WallBoxTransaction with _$WallBoxTransaction implements DatabaseModel {
  /// In this class we keep every time somebody charged their vehicle at a wallbox
  /// We keep data about the begin and end oft the charging process and can recieve how much power was used
  ///
  /// This class stores completed processes only!
  WallBoxTransaction({
    required this.start,
    required this.stop,
    this.isPaid = false,
  }) {
    assert(
      durationSeconds >= 0,
      'ERROR while creating $WallBoxTransaction:\n duration $durationSeconds is nonpositive but should be pocRsitive',
    );
    assert(
      start.tagID == tagID && stop.tagID == tagID,
      'ERROR while creating $WallBoxTransaction:\n id2s dont match up:\n* Process: $tagID\n* start: ${start.tagID},\n* Stop:${stop.tagID}',
    );
    if (!UserMasterData.repo.hasEntry(tagID)) {
      UserMasterData.repo.createOrUpdate(UserMasterData(tagID: tagID));
    }
  }
  @override
  final bool isPaid;

  /// access function for conversion to JSON
  factory WallBoxTransaction.fromJson(Map<String, Object?> json) =>
      _$WallBoxTransactionFromJson(json);

  /// access function for conversion from JSON
  Map<String, dynamic> toJson() => _$WallBoxTransactionToJson(this);

  /// The Reposiory to save and load [WallBoxTransaction]s to/ from the database
  static final SimulationRepo<WallBoxTransaction> repo =
      SimulationRepo<WallBoxTransaction>('transactions');

  /// The start of the [WallBoxTransaction]
  @override
  final ChargingEvent start;

  /// The end of the [WallBoxTransaction]
  @override
  late ChargingEvent stop;

  /// The tagID wich is used to identifie the user who charged
  String get tagID => start.tagID;

  /// Getter for when did the transaction start
  DateTime get startTimeStamp => start.timeStamp;

  /// Getter for when did the transaction end
  DateTime get stopTimeStamp => stop.timeStamp;

  /// returns a formatted date string for the starting date
  ///
  /// - [includeTime] defines if the hours and minutes are sdisplayed aswell
  String startTimeDisplay([bool includeTime = false]) =>
      start.timeStampDisplay(includeTime);

  /// returns a formatted date string for the ending date
  ///
  /// - [includeTime] defines if the hours and minutes are sdisplayed aswell
  String stopTimeDisplay([bool includeTime = false]) =>
      stop.timeStampDisplay(includeTime);

  /// The total time the [WallBoxTransaction] took
  int get durationSeconds => stop.timeSeconds - start.timeSeconds;

  /// How much Power was consumed during this [WallBoxTransaction]?
  int get powerUsageWh => (stop.powerLevelWh - start.powerLevelWh);

  /// converts the power usage into kWh
  double get powerUsageKiloWh {
    return powerUsageWh / 1000;
  }

  /// returns the price to pay in cents depending on the user's price per kWh
  int get costsInCent => (user.pricePerkWhInCents * powerUsageKiloWh).round();

  /// display getter for power usage
  String get powerUsageKWhDisplay =>
      '${(powerUsageKiloWh).toStringAsFixed(2)} kWh';

  /// the user associated with the Transactions tagID
  UserMasterData get user => UserMasterData.repo.getById(tagID)!;

  /// The associated user's full name
  String get username => user.fullName ?? '[unbekannt]';

  /// displays the Transactions costs in €
  String get costsDisplay =>
      '${(costsInCent.toDouble() / 100).toStringAsFixed(2)} €';

  @override
  String get repoID =>
      '$tagID.${startTimeStamp.toIso8601String().replaceAll(':', '-')}';

  /// Returns all Transactions that have the passed [tagID]
  static List<WallBoxTransaction> allOfTagID(String tagID) => repo
      .getAll()
      .where(
        (element) => element.tagID == tagID,
      )
      .toList();
}
//  ####### #     # ####### #     # #######
//  #       #     # #       ##    #    #
//  #       #     # #       # #   #    #
//  #####   #     # #####   #  #  #    #
//  #        #   #  #       #   # #    #
//  #         # #   #       #    ##    #
//  #######    #    ####### #     #    #

/// Detailed information about a start or end of a [WallBoxTransaction]
@freezed
@JsonSerializable()
class ChargingEvent with _$ChargingEvent {
  /// Detailed information about a start or end of a [WallBoxTransaction]
  ChargingEvent({
    required this.tagID,
    required this.timeStamp,
    required this.powerLevelWh,
  });

  /// returns a formatted date string for this [ChargingEvent]
  ///
  /// - [includeTime] defines if the hours and minutes are displayed aswell
  String timeStampDisplay([bool includeTime = true]) => includeTime
      ? Utility.niceFullDateString(timeStamp)
      : Utility.niceDateString(timeStamp);

  /// access function for conversion from JSON
  factory ChargingEvent.fromJson(Map<String, dynamic> json) =>
      _$ChargingEventFromJson(json);

  /// access function for conversion to JSON
  Map<String, dynamic> toJson() => _$ChargingEventToJson(this);

  /// The tagID wich is used to identifie the user who charged
  @override
  late final String tagID;

  /// The exact time this event happened
  @override
  late final DateTime timeStamp;

  /// The Wallboxes PowerLevel in Wh when this event happened
  @override
  late final int powerLevelWh;

  /// The seconds of the event aafter epoch
  int get timeSeconds => (timeStamp.millisecondsSinceEpoch / 1000).floor();
}
