import 'package:wallbox_logs/back_layer/appdata.dart';
import 'package:wallbox_logs/back_layer/model_repos/simulation_repo/user_master/simulation_repo.dart';
import 'package:wallbox_logs/mid_layer/services/database_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:wallbox_logs/mid_layer/services/transaction/wall_box_transaction.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_master_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_master_data.g.dart';

/// Ways to refer to a person of different genders
enum Titles {
  /// Male
  mrs(label: 'Herr'),

  /// Female
  mr(label: 'Frau'),

  /// Diverse
  div(label: 'divers');

  ///a String representation for the title
  final String label;
  const Titles({required this.label});
}

/// Master Data (Stammdaten) for a wallbox user.
/// - [tagID] (required) :  the users tag ID (the same that is noted in Wallbox log files)
/// - [individualPricePerkWhInCents] : How much should this person pay per kWh ? if null a default price will be used
@freezed
@JsonSerializable()
class UserMasterData with _$UserMasterData implements DatabaseModel {
  /// Master Data (Stammdaten) for a wallbox user.
  /// - [tagID] (required) :  the users tag ID (the same that is noted in Wallboy log files)
  /// - [individualPricePerkWhInCents] : How much should this person pay per kWh ? if null a default price will be used
  UserMasterData({
    required this.tagID,

    this.title = Titles.div,
    this.prename,
    this.surname,
    this.company,
    this.individualPricePerkWhInCents,
    this.email,
    this.phoneNumber,
    this.streetAndNumber,
    this.postCode,
    this.city,
  });

  /// The Reposiory to save and load [UserMasterData] to/ from the database
  static final SimulationRepo<UserMasterData> repo = SimulationRepo(
    'user_repo',
  );

  /// Placeolder for missing names
  static const unknown = '[unbekannt]';

  /// returns a list containing every company registered in the repository
  static List<String> get companies {
    List<String> companies = List.empty(growable: true);
    for (var user in repo.cache.values) {
      if (user.company != null && !companies.contains(user.company)) {
        companies.add(user.company!);
      }
    }

    return companies;
  }

  /// creates a [UserMasterData] object from a valid json Map
  factory UserMasterData.fromJson(Map<String, Object?> json) =>
      _$UserMasterDataFromJson(json);

  /// converts this to a json map
  Map<String, dynamic> toJson() => _$UserMasterDataToJson(this);

  List<WallBoxTransaction> get transactions =>
      WallBoxTransaction.allOfTagID(tagID);

  Map<DateTime, List<WallBoxTransaction>> transactionsByMonth([
    bool includePaid = false,
  ]) {
    final all = transactions;
    Map<DateTime, List<WallBoxTransaction>> result = {};
    for (int i = 0; i < all.length; i++) {
      final currentTransaction = all[i];
      if (!includePaid && currentTransaction.isPaid) continue;
      final currentDate = currentTransaction.startTimeStamp;
      final DateTime keyDate = DateTime(currentDate.year, currentDate.month);

      if (!result.containsKey(keyDate))
        result[keyDate] = List.empty(growable: true);
      result[keyDate]!.add(currentTransaction);
    }
    return result;
  }

  int get fullPowerUsageWh => transactions.fold<int>(
    0,
    (previousValue, transaction) => previousValue + transaction.powerUsageWh,
  );

  String get fullPowerUsageDisplay =>
      '${(fullPowerUsageWh.toDouble() / 1000).toStringAsFixed(2)} kWh';

  int get fullCostsInCent => transactions.fold(
    0,
    (previousValue, transaction) => previousValue + transaction.costsInCent,
  );

  String get fullCostsDisplay =>
      '${(fullCostsInCent.toDouble() / 100).toStringAsFixed(2)} €';

  int get pricePerkWhInCents =>
      individualPricePerkWhInCents ?? AppData.companyPrice(company);

  String get pricePerkWhDisplay =>
      '${(pricePerkWhInCents.toDouble() / 100).toStringAsFixed(2)} €';

  @override
  final Titles title;
  @override
  final String tagID;
  @override
  final String? prename;
  @override
  final String? surname;
  @override
  final String? company;
  @override
  final int? individualPricePerkWhInCents;
  @override
  final String? email;
  @override
  final String? phoneNumber;
  @override
  final String? streetAndNumber;
  @override
  final String? postCode;
  @override
  final String? city;

  @override
  String get repoID => tagID;

  /// - if both set, returns "prename surname".
  /// - If one is unset, it's replaced with '[unbekannt]'
  /// - If both unset just returns '[unbekannt]'
  String? get fullName {
    return prename == null && surname == null
        ? unknown
        : '${prename ?? unknown} ${surname ?? unknown}';
  }

  /// The user's full formatted address if available
  String? get address =>
      (streetAndNumber != null && postCode != null && city != null)
      ? '$streetAndNumber\n$postCode $city'
      : null;
}
