import 'package:wallbox_logs/back_layer/model_repos/simulation_repo/user_master/simulation_repo.dart';
import 'package:wallbox_logs/mid_layer/models/database_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_master_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_master_data.g.dart';

/// Ways to refer to a person of different genders
enum Titles {
  /// Male
  mrs(label: 'Herr'),

  /// Female
  mr(label: 'Frau'),

  /// Diverse
  div(label: 'divers')
  ;

  final String label;
  const Titles({required this.label});
}

/// Master Data (Stammdaten) for a wallbox user.
/// - [tagID] (required) :  the users tag ID (the same that is noted in Wallbox log files)
/// - [individualPricePerkWhInCents] : How much should this person pay per kWh ? if null a default price will be used
@freezed
@JsonSerializable()
class UserMasterData with _$UserMasterData implements DatabaseModel {
  /// Master Data (Stammdaten) for a wallbox user.
  /// - [tagID] (required) :  the users tag ID (the same that is noted in Wallboy log files)
  /// - [individualPricePerkWhInCents] : How much should this person pay per kWh ? if null a default price will be used
  UserMasterData({
    required this.tagID,

    this.title = Titles.div,
    this.prename,
    this.surname,
    this.company,
    this.individualPricePerkWhInCents,
    this.email,
    this.phoneNumber,
    this.streetAndNumber,
    this.postCode,
    this.city,
  });

  static final SimulationRepo<UserMasterData> repo = SimulationRepo(
    'user_repo',
  );
  static const unknown = '[unbekannt]';
  static List<String> get companies {
    List<String> companies = List.empty(growable: true);
    for (var user in repo.cache.values) {
      if (user is UserMasterData && user.company != null) {
        companies.add(user.company!);
      }
    }

    return companies;
  }

  /// creates a [UserMasterData] object from a valid json Map
  factory UserMasterData.fromJson(Map<String, Object?> json) =>
      _$UserMasterDataFromJson(json);

  /// converts this to a json map
  Map<String, dynamic> toJson() => _$UserMasterDataToJson(this);

  @override
  final Titles title;
  @override
  final String tagID;
  @override
  final String? prename;
  @override
  final String? surname;
  @override
  final String? company;
  @override
  final int? individualPricePerkWhInCents;
  @override
  final String? email;
  @override
  final String? phoneNumber;
  @override
  final String? streetAndNumber;
  @override
  final String? postCode;
  @override
  final String? city;

  @override
  String get repoID => tagID;

  String? get fullName {
    return prename == null && surname == null
        ? unknown
        : '${prename ?? unknown} ${surname ?? unknown}';
  }

  /// The user's full formatted address if available
  String? get address =>
      (streetAndNumber != null && postCode != null && city != null)
      ? '$streetAndNumber\n$postCode $city'
      : null;
}
