import 'package:flutter/material.dart';
import 'package:wallbox_logs/back_layer/model_repos/database_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_master_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_master_data.g.dart';

enum Titles { mrs, mr, div, none }

@freezed
@JsonSerializable()
class UserMasterData extends DatabaseModel with _$UserMasterData {
  UserMasterData({
    this.title = Titles.none,
    required this.tagID,
    this.prename,
    this.surname,
    this.company,
    this.individualPrice,
    this.email,
    this.phoneNumber,
    this.streetAndNumber,
    this.postCode,
    this.city,
  });

  factory UserMasterData.fromJson(Map<String, Object?> json) =>
      _$UserMasterDataFromJson(json);

  final Titles title;
  final String tagID;
  final String? prename;
  final String? surname;
  final String? company;
  final double? individualPrice;

  final String? email;
  final String? phoneNumber;
  final String? streetAndNumber;
  final String? postCode;
  final String? city;

  @override
  String get id => tagID;

  String? get address => "$streetAndNumber\n$postCode $city";

  @override
  Map<String, dynamic> toJson() => _$UserMasterDataToJson(this);
}
