import 'package:wallbox_logs/back_layer/database/database_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_master_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_master_data.g.dart';

@freezed
@JsonSerializable()
class UserMasterData extends DatabaseModel with _$UserMasterData {
  UserMasterData({
    required this.tagID,
    this.name,
    this.company,
    this.individualPrice,
  });

  factory UserMasterData.fromJson(Map<String, Object?> json) =>
      _$UserMasterDataFromJson(json);

  final String tagID;
  final String? name;
  final String? company;
  final double? individualPrice;

  @override
  Map<String, dynamic> toJson() => _$UserMasterDataToJson(this);
}
